package com.example.anitracker.vnObjects;

import java.util.Map;

public class VNLanguage {
    public static final Map<String, String> languageMap = Map.<String, String>ofEntries(
            Map.entry("ar", "Arabic"),
            Map.entry("eu", "Basque"),
            Map.entry("be", "Belarusian"),
            Map.entry("bg", "Bulgarian"),
            Map.entry("ca", "Catalan"),
            Map.entry("ck", "Cherokee"),
            Map.entry("zh", "Chinese"),
            Map.entry("zh-Hans", "Chinese (simplified)"),
            Map.entry("zh-Hant", "Chinese (traditional)"),
            Map.entry("hr", "Croatian"),
            Map.entry("cs", "Czech"),
            Map.entry("da", "Danish"),
            Map.entry("nl", "Dutch"),
            Map.entry("en", "English"),
            Map.entry("eo", "Esperanto"),
            Map.entry("fi", "Finnish"),
            Map.entry("fr", "French"),
            Map.entry("de", "German"),
            Map.entry("el", "Greek"),
            Map.entry("he", "Hebrew"),
            Map.entry("hi", "Hindi"),
            Map.entry("hu", "Hungarian"),
            Map.entry("ga", "Irish"),
            Map.entry("id", "Indonesian"),
            Map.entry("it", "Italian"),
            Map.entry("iu", "Inuktitut"),
            Map.entry("ja", "Japanese"),
            Map.entry("ko", "Korean"),
            Map.entry("la", "Latin"),
            Map.entry("lv", "Latvian"),
            Map.entry("lt", "Lithuanian"),
            Map.entry("mk", "Macedonian"),
            Map.entry("ms", "Malay"),
            Map.entry("no", "Norwegian"),
            Map.entry("fa", "Persian"),
            Map.entry("pl", "Polish"),
            Map.entry("pt-br", "Portuguese (Brazil)"),
            Map.entry("pt-pt", "Portuguese (Portugal)"),
            Map.entry("ro", "Romanian"),
            Map.entry("ru", "Russian"),
            Map.entry("gd", "Scottish Gaelic"),
            Map.entry("sr", "Serbian"),
            Map.entry("sk", "Slovak"),
            Map.entry("sl", "Slovene"),
            Map.entry("es", "Spanish"),
            Map.entry("sv", "Swedish"),
            Map.entry("ta", "Tagalog"),
            Map.entry("th", "Thai"),
            Map.entry("tr", "Turkish"),
            Map.entry("uk", "Ukrainian"),
            Map.entry("ur", "Urdu"),
            Map.entry("vi", "Vietnamese")
    );
}
