package com.example.anitracker.vnObjects;

import java.util.Map;

public class VNPlatform {
    public static Map<String, String> platformMap = Map.<String, String>ofEntries(
            Map.entry("win", "Windows"),
            Map.entry("lin", "Linux"),
            Map.entry("mac", "Mac OS"),
            Map.entry("web", "Website"),
            Map.entry("tdo", "3DO"),
            Map.entry("ios", "Apple iProduct"),
            Map.entry("and", "Android"),
            Map.entry("bdp", "Blu-ray Player"),
            Map.entry("dos", "DOS"),
            Map.entry("dvd", "DVD Player"),
            Map.entry("drc", "Dreamcast"),
            Map.entry("nes", "Famicom"),
            Map.entry("sfc", "Super Famicom"),
            Map.entry("fm7", "FM-7"),
            Map.entry("fm8", "FM-8"),
            Map.entry("fmt", "FM Towns"),
            Map.entry("gba", "Game Boy Advance"),
            Map.entry("gbc", "Game Boy Color"),
            Map.entry("msx", "MSX"),
            Map.entry("nds", "Nintendo DS"),
            Map.entry("swi", "Nintendo Switch"),
            Map.entry("wii", "Nintendo Wii"),
            Map.entry("wiu", "Nintendo Wii U"),
            Map.entry("n3d", "Nintendo 3DS"),
            Map.entry("p88", "PC-88"),
            Map.entry("pce", "PC Engine"),
            Map.entry("pcf", "PC-FX"),
            Map.entry("psp", "PlayStation Portable"),
            Map.entry("ps1", "PlayStation 1"),
            Map.entry("ps2", "PlayStation 2"),
            Map.entry("ps3", "PlayStation 3"),
            Map.entry("ps4", "PlayStation 4"),
            Map.entry("ps5", "PlayStation 5"),
            Map.entry("psv", "PlayStation Vita"),
            Map.entry("smd", "Sega Mega Drive"),
            Map.entry("scd", "Sega Mega-CD"),
            Map.entry("sat", "Sega Saturn"),
            Map.entry("vnd", "VNDS"),
            Map.entry("x1s", "Sharp X1"),
            Map.entry("x68", "Sharp X68000"),
            Map.entry("xb1", "Xbox"),
            Map.entry("xb3", "Xbox 360"),
            Map.entry("xbo", "Xbox One"),
            Map.entry("xxs", "Xbox X/S"),
            Map.entry("mob", "Other (mobile)"),
            Map.entry("oth", "Other")
    );
}
