fragment shortDetail on Media {
    title {
        userPreferred
    }
    coverImage {
        large
    }
    format
    id
    status
    type
}

fragment mediumDetail on Media {
    ...shortDetail
    averageScore
    genres
    favourites
    startDate {
        year
    }
}

fragment detail on Media {
    ...mediumDetail
    title {
        userPreferred
        romaji
        native
        english
    }
    startDate {
        year
        month
        day
    }
    endDate {
        year
        month
        day
    }
    description(asHtml: true)
    bannerImage
    trailer {
        id
        site
        thumbnail
    }
    synonyms
    source
    meanScore
    popularity
    hashtag
    tags {
        name
        rank
        isMediaSpoiler
        isGeneralSpoiler
    }
}

fragment animeShortDetail on Media {
    ...mediumDetail
    season
    episodes
    duration

    nextAiringEpisode {
        timeUntilAiring
        episode
    }
}

fragment animeDetail on Media {
    ...detail
    ...animeShortDetail
    studios {
        edges {
            isMain
            node {
                name
                isAnimationStudio
            }
        }
    }
}

fragment mangaShortDetail on Media {
    ...mediumDetail
    endDate {
        year
    }
    volumes
}

fragment mangaDetail on Media {
    ...detail
    ...mangaShortDetail
    chapters
}

fragment shortCharDetail on Character {
    name {
        userPreferred
    }
    id
    image {
        large
    }
}

fragment charDetail on Character {
    ...shortCharDetail
    name {
        first
        middle
        last
        full
        native
        userPreferred
        alternative
        alternativeSpoiler
    }
    description(asHtml: true)
    gender
    dateOfBirth {
        year
        month
        day
    }
    age
    bloodType
    favourites
}

fragment shortStaffDetail on Staff {
    id
    name {
        userPreferred
    }
    image{
        large
    }
}

fragment staffDetail on Staff {
    ...shortStaffDetail
    name {
        first
        middle
        last
        full
        native
        alternative
        userPreferred
    }
    languageV2
    description(asHtml: true)
    primaryOccupations
    gender
    dateOfBirth {
        year
        month
        day
    }
    dateOfDeath {
        year
        month
        day
    }
    age
    yearsActive
    homeTown
    bloodType
    favourites
}

query AnimeSearchPage ($pageNo : Int!, $userSearch : String, $sort : [MediaSort], $genres : [String], $tags : [String]) {
    Page (page: $pageNo, perPage: 50){
        media (search: $userSearch, sort: $sort, type: ANIME, genre_in: $genres, tag_in: $tags) {
            ...animeShortDetail
            studios(isMain:true){
                nodes{
                    name
                }
            }
        }
    }
}

query MangaSearchPage ($pageNo : Int!, $userSearch : String, $sort:[MediaSort], $genres : [String], $tags : [String]) {
    Page (page: $pageNo, perPage: 50){
        media (search: $userSearch, sort: $sort, type: MANGA, genre_in: $genres, tag_in: $tags){
            ...mangaShortDetail
        }
    }
}

query AnimeMoreDetails($id : Int!){
    Media(id: $id, type: ANIME) {
        ...animeDetail
    }
}

query MangaMoreDetails($id : Int!) {
    Media(id: $id, type: MANGA) {
        ...mangaDetail
    }
}

query CharacterPage($mediaId : Int!, $pageNo : Int!, $language : StaffLanguage!) {
    Media(id: $mediaId) {
        characters(page: $pageNo, perPage: 25, sort: [ROLE, RELEVANCE, ID]) {
            edges {
                role
                voiceActorRoles(language: $language) {
                    roleNotes
                    voiceActor {
                        ...shortStaffDetail
                    }
                }
                node {
                    ...shortCharDetail
                }
            }
        }
    }
}

query StaffPage ($mediaId : Int!, $pageNo : Int!) {
    Media(id: $mediaId) {
        staff(page: $pageNo, perPage: 25, sort: [RELEVANCE, ROLE]) {
            edges {
                role
                node {
                    ...shortStaffDetail
                }
            }
        }
    }
}

query StaffDetail($id : Int!) {
    Staff(id : $id) {
        ...staffDetail
    }
}

query StaffChars($id: Int!, $page: Int!) {
    Staff(id : $id) {
        characterMedia(sort: FAVOURITES_DESC, page: $page, perPage: 25) {
            edges {
                characterRole
                characters {
                    ...shortCharDetail
                }
                node {
                    ...shortDetail
                }
            }
        }
    }
}

query StaffRoles($id: Int!, $page: Int!) {
    Staff(id : $id) {
        staffMedia(sort: POPULARITY_DESC, page: $page, perPage: 25) {
            edges {
                staffRole
                node {
                    ...shortDetail
                }
            }
        }
    }
}

query RelationsPage($mediaId : Int!) {
    Media(id: $mediaId) {
        relations {
            edges {
                relationType
                node {
                    ...shortDetail
                }
            }
        }
    }
}

query CharacterDetail($id : Int!) {
    Character(id: $id) {
       ...charDetail
    }
}

query CharacterRoles ($id : Int!, $page : Int!) {
    Character(id: $id) {
        media(sort: POPULARITY_DESC, page: $page, perPage: 25) {
            edges {
                characterRole
                node {
                    ...shortDetail
                }
            }
        }
    }
}

query MediaAttributes {
    GenreCollection
    MediaTagCollection {
        name
    }
}